routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\OutofStockController;
use App\Http\Controllers\PredictionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('items', ItemController::class);
Route::resource('sales', SalesController::class);
Route::resource('outofstock', OutofStockController::class);
Route::resource('predict', SalesController::class);

Route::get('sales.weekly', [SalesController::class, 'weekly']);
Route::post('sales.weekly', [SalesController::class, 'weekly'])->name('date');

Route::get('sales.monthly', [SalesController::class, 'monthly']);
Route::post('sales.monthly', [SalesController::class, 'monthly'])->name('monthdate');

Route::get('sales.compare', [SalesController::class, 'compare']);
Route::post('sales.compare', [SalesController::class, 'compare'])->name('comparedate');

Route::get('sales.predict', [PredictionController::class, 'predict']);
Route::post('sales.predict', [PredictionController::class, 'predict'])->name('predict');

app/Http/Controllers/OutofStockController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Item;

class OutofStockController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::where('quantity', 0)->get();
        return view('outofstock.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items = Item::findOrFail($id);
        return view('outofstock.edit', compact('items'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = $request->validate([
            'quantity' => 'required|max:255',
        ]);
        Item::whereId($id)->update($updateData);
        return redirect('/outofstock')->with('message', 'Item has successfully been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $items = Item::findOrFail($id);
        $items->delete();

        return redirect('/outofstock')->with('completed', 'Data has been deleted');
    }
}

resources/views/outofstock/edit.blade.php
@extends('layouts.app')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<div class="card push-top">
  <div class="card-header">
    Restock
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('outofstock.update', $items->id) }}">
              @csrf
              @method('PATCH')
          <div class="form-group">
              <label for="quantity">Quantity</label>
              <input type="text" class="form-control" name="quantity" value="{{$items->quantity}}"/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Update Item</button>
      </form>
  </div>
</div>
@endsection

resources/views/outofstock/index.blade.php
@extends('layouts.app')

@section('content')

<div class="push-top">
  @if(session()->get('message'))
    <div class="alert alert-success">
      {{ session()->get('message') }}  
    </div>
  @endif
</div>

<div class="push-top">
  @if(session()->get('completed'))
    <div class="alert alert-danger">
      {{ session()->get('completed') }}  
    </div>
  @endif
</div>

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
<table class="table">
    <thead>
        <tr class="table-warning">
          <td>ID</td>
          <td>Item ID</td>
          <td>Item Name</td>
          <td>Quantity</td>
          <td class="text-center" style="width:10vw">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($items as $item)
        <tr>
            <td>{{$item->id}}</td>
            <td>{{$item->item_id}}</td>
            <td>{{$item->item_name}}</td>
            <td>{{$item->quantity}}</td>
            <td class="text-center">
                <a href="{{ route('outofstock.edit', $item->id)}}" class="btn btn-primary btn-sm">Edit</a>
                <form action="{{ route('outofstock.destroy', $item->id)}}" method="post" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                  </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div>

@endsection