routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\OutofStockController;
use App\Http\Controllers\PredictionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('items', ItemController::class);
Route::resource('sales', SalesController::class);
Route::resource('outofstock', OutofStockController::class);
Route::resource('predict', SalesController::class);

Route::get('sales.weekly', [SalesController::class, 'weekly']);
Route::post('sales.weekly', [SalesController::class, 'weekly'])->name('date');

Route::get('sales.monthly', [SalesController::class, 'monthly']);
Route::post('sales.monthly', [SalesController::class, 'monthly'])->name('monthdate');

Route::get('sales.compare', [SalesController::class, 'compare']);
Route::post('sales.compare', [SalesController::class, 'compare'])->name('comparedate');

Route::get('sales.predict', [PredictionController::class, 'predict']);
Route::post('sales.predict', [PredictionController::class, 'predict'])->name('predict');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $table = 'items';
    protected $fillable = ['item_id', 'item_name', 'category' ,'item_desc', 'price','quantity'];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Item;
use DB;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::orderBy('item_id', 'asc')->get();
        $restock_item = DB::table('items')->where('quantity', 0)->get();
        return view('Items.index', compact('items', 'restock_item'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $storeData = $request->validate([
            'item_id' => 'required|max:255',
            'item_name' => 'required|max:255',
            'item_desc' => 'required|max:255',
            'item_desc' => 'required|max:255',
            'price' => 'required|max:255',
            'quantity' => 'required|max:255',
        ]);
        $storeData = $request->all();
        $items = Item::updateOrCreate(  ['item_id' => $request->item_id],
                                        ['item_id' => $request->item_id,
                                        'item_name' => $request->item_name,
                                        'category' => $request->category,
                                        'item_desc' => $request->item_desc,
                                        'price' => $request->price,
                                        'quantity' => $request->quantity,]);

        return redirect('items/create')->with('success', 'Item has successfully been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items = Item::findOrFail($id);
        return view('Items.edit', compact('items'))->with('message', 'Item has successfully been updated!');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = $request->validate([
            'item_id' => 'required|max:255',
            'item_name' => 'required|max:255',
            'category' => 'required|max:255',
            'item_desc' => 'required|max:255',
            'price' => 'required|max:255',
            'quantity' => 'required|max:255',
        ]);
        Item::whereId($id)->update($updateData);
        return redirect('/items')->with('message', 'Item has successfully been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $items = Item::findOrFail($id);
        $items->delete();

        return redirect('/items')->with('delete', 'Data has been deleted');
    }
}

resources/views/Items/create.blade.php
@extends('layouts.app')

@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<div class="card push-top">
  <div class="card-header">
    <h5>
      Add Items
    </h5>
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('items.store') }}">
          <div class="form-group">
                @csrf
              <label for="item_id">Item ID</label>
              <input type="text" class="form-control" name="item_id"/>
          </div>
          <div class="form-group">
              <label for="item_name">Item Name</label>
              <input type="text" class="form-control" name="item_name"/>
          </div>
          <div class="form-group">
              <label for="category">Category</label>
              <select class="js-example-basic-single form-control" style="width:100%" name="category">
                  <option value="" disabled selected>--Select--</option>
                  <option value="Medicine">Medicine</option>
                  <option value="Medical Equipment">Medical Equipment</option>
                  <option value="Medical Equipment">Medical Ointment</option>
                  <option value="Skincare Products">Skincare Products</option>
              </select>
          </div>
          <div class="form-group">
              <label for="item_desc">Item Description</label>
              <input type="text" class="form-control" name="item_desc"/>
          </div>
          <div class="form-group">
              <label for="price">Price</label>
              <input type="text" class="form-control" name="price"/>
          </div>
          <div class="form-group">
              <label for="quantity">Quantity</label>
              <input type="text" class="form-control" name="quantity"/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Create Item</button>
      </form>   
       
          <a href="{{url('items')}}" class="btn btn-block btn-info" style="margin-top:25px">Show Item List</a>
  </div>
</div>

<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/Items/edit.blade.php
@extends('layouts.app')

@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<div class="card push-top">
  <div class="card-header">
    Edit & Update
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('items.update', $items->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="item_id">Item ID</label>
              <input type="text" class="form-control" name="item_id" value="{{$items->item_id}}"/>
          </div>
          <div class="form-group">
              <label for="item_name">Item Name</label>
              <input type="text" class="form-control" name="item_name" value="{{$items->item_name}}"/>
          </div>
          <div class="form-group">
              <label for="category">Category</label>
              <select class="js-example-basic-single form-control" style="width:100%" name="category">
                  <option value="{{$items->category}}" selected>{{$items->category}}</option>
                  @if($items->category == "Medicine")
                  <option value="Medical Equipment">Medical Equipment</option>
                  <option value="Medical Ointment">Medical Ointment</option>
                  <option value="Skincare Products">Skincare Products</option>
                  @elseif($items->category == "Medical Equipment")
                  <option value="Medicine">Medicine</option>
                  <option value="Medical Ointment">Medical Ointment</option>
                  <option value="Skincare Products">Skincare Products</option>
                  @elseif($items->category == "Medical Ointment")
                  <option value="Medicine">Medicine</option>
                  <option value="Medical Equipment">Medical Equipment</option>
                  <option value="Skincare Products">Skincare Products</option>
                  @else
                  <option value="Medicine">Medicine</option>
                  <option value="Medical Equipment">Medical Equipment</option>
                  <option value="Medical Ointment">Medical Ointment</option>
                  @endif
              </select>
          </div>
          <div class="form-group">
              <label for="item_desc">Item Description</label>
              <input type="text" class="form-control" name="item_desc" value="{{$items->item_desc}}"/>
          </div>
          <div class="form-group">
              <label for="price">Price</label>
              <input type="text" class="form-control" name="price" value="{{$items->price}}"/>
          </div>
          <div class="form-group">
              <label for="quantity">Quantity</label>
              <input type="text" class="form-control" name="quantity" value="{{$items->quantity}}"/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Update Item</button>
      </form>
  </div>
</div>

<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/Items/index.blade.php
@extends('layouts.app')

@section('content')

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="push-top">
  @if(session()->get('delete'))
    <div class="alert alert-danger">
      {{ session()->get('delete') }}  
    </div>
  @endif
</div>

<div class="push-top">
  @if(session()->get('message'))
    <div class="alert alert-success">
      {{ session()->get('message') }}  
    </div>
  @endif
</div>

<div class="push-top">
  @foreach($restock_item as $item)
      @if($item->quantity == 0)
        <div class="alert alert-info">
          Please Restock {{$item->item_name}} !
        </div>
      @endif
    @endforeach
</div>

  <table class="table">
    <thead>
        <tr class="table-warning">
          <td>ID</td>
          <td>Item ID</td>
          <td>Item Name</td>
          <td>Category</td>
          <td>Item Description</td>
          <td>Price</td>
          <td>Quantity</td>
          <td class="text-center" style="width:10vw">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($items as $item)
        <tr>
            <td>{{$item->id}}</td>
            <td>{{$item->item_id}}</td>
            <td>{{$item->item_name}}</td>
            <td>{{$item->category}}</td>
            <td>{{$item->item_desc}}</td>
            <td>RM {{$item->price}}</td>
            <td>{{$item->quantity}} pcs</td>
            <td class="text-center">
                <a href="{{ route('items.edit', $item->id)}}" class="btn btn-primary btn-sm">Edit</a>
                <form action="{{ route('items.destroy', $item->id)}}" method="post" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                  </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection