routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\SalesController;
use App\Http\Controllers\OutofStockController;
use App\Http\Controllers\PredictionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('items', ItemController::class);
Route::resource('sales', SalesController::class);
Route::resource('outofstock', OutofStockController::class);
Route::resource('predict', SalesController::class);

Route::get('sales.weekly', [SalesController::class, 'weekly']);
Route::post('sales.weekly', [SalesController::class, 'weekly'])->name('date');

Route::get('sales.monthly', [SalesController::class, 'monthly']);
Route::post('sales.monthly', [SalesController::class, 'monthly'])->name('monthdate');

Route::get('sales.compare', [SalesController::class, 'compare']);
Route::post('sales.compare', [SalesController::class, 'compare'])->name('comparedate');

Route::get('sales.predict', [PredictionController::class, 'predict']);
Route::post('sales.predict', [PredictionController::class, 'predict'])->name('predict');

app/Models/Sales.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sales extends Model
{
    use HasFactory;
    protected $table = 'sales';
    protected $fillable = ['sold_id', 'sold_name', 'sold_date', 'category', 'sales_amount', 'sold_quantity'];
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Sales;
use Carbon\Carbon;
use DB;
use App\Models\Item;
use Redirect;

class SalesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sale = Sales::all();
        $items = Item::all();
        $restock_item = DB::table('items')->where('quantity', 0)->get();
        return view('Sales.index', compact('sale', 'items', 'restock_item'));
    }

    public function getindex()
    {
        return view('sales.create', compact('items'));
    }

        //Display weekly sales report
        public function weekly(Request $request) 
        {   
            $dt = Carbon::create($request['from_date']);
            $storeData = $request->all();
   
            $sum = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endofWeek()])
            ->sum('sales_amount');
    
            $first = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endofWeek()])->first();
            $latest = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endofWeek()])->orderBy('sold_date', 'desc')->first();
            $count = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endofWeek()])->orderBy('sold_date', 'desc')->Count();
            $getdate = $request['from_date'];
            
            $current_week = Sales::whereBetween('sold_date', [$request['from_date'], $dt->endofWeek()])->OrderBy('sold_date')->get();
            if($request->key == "key"){
                $fileName = "Weekly_$first->sold_date/_$latest->sold_date.csv";
             
                     $headers = array(
                         "Content-type"        => "text/csv",
                         "Content-Disposition" => "attachment; filename=$fileName",
                         "Pragma"              => "no-cache",
                         "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
                         "Expires"             => "0"
                     );
             
                     $columns = array('sold_id', 'sold_name', 'sold_date', 'sales_amount', 'sold_quantity');
             
                     $callback = function() use($current_week, $columns) {
                         $file = fopen('php://output', 'w');
                         fputcsv($file, $columns);
             
                         foreach ($current_week as $csv) {
                             $row['sold_id']  = $csv->sold_id;
                             $row['sold_name']    = $csv->sold_name;
                             $row['sold_date']    = $csv->sold_date;
                             $row['sales_amount']  = $csv->sales_amount;
                             $row['sold_quantity']  = $csv->sold_quantity;
             
                             fputcsv($file, array($row['sold_id'], $row['sold_name'], $row['sold_date'], $row['sales_amount'], $row['sold_quantity']));
                         }
             
                         fclose($file);
                     };
                     return response()->stream($callback, 200, $headers);
            }
            return view('sales.weekly', ['sale' => $current_week, 'sum' => $sum, 'first' => $first, 'latest' => $latest, 'count' => $count, 'getdate' => $getdate]);
        }
    
        //Display monthly sales report
        public function monthly(Request $request) 
        {   
            $dt = Carbon::create($request['from_date']);
    
            $sum = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endOfMonth()])
            ->sum('sales_amount');
            $getdate = $request['from_date'];
    
            $first = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endOfMonth()])->first();
            $latest = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endOfMonth()])->orderBy('sold_date', 'desc')->first();
            $count = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $dt->endOfMonth()])->orderBy('sold_date', 'desc')->Count();
            $current_month = Sales::whereBetween('sold_date', [$request['from_date'], $dt->endOfMonth()])->OrderBy('sold_date')->get();
    
            if($request->key == "monthkey"){
                $fileName = "Monthly_$first->sold_date/_$latest->sold_date.csv";
             
                     $headers = array(
                         "Content-type"        => "text/csv",
                         "Content-Disposition" => "attachment; filename=$fileName",
                         "Pragma"              => "no-cache",
                         "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
                         "Expires"             => "0"
                     );
             
                     $columns = array('sold_id', 'sold_name', 'sold_date', 'sales_amount', 'sold_quantity');
             
                     $callback = function() use($current_month, $columns) {
                         $file = fopen('php://output', 'w');
                         fputcsv($file, $columns);
             
                         foreach ($current_month as $csv) {
                             $row['sold_id']  = $csv->sold_id;
                             $row['sold_name']    = $csv->sold_name;
                             $row['sold_date']    = $csv->sold_date;
                             $row['sales_amount']  = $csv->sales_amount;
                             $row['sold_quantity']  = $csv->sold_quantity;
             
                             fputcsv($file, array($row['sold_id'], $row['sold_name'], $row['sold_date'], $row['sales_amount'], $row['sold_quantity']));
                         }
             
                         fclose($file);
                     };
                     return response()->stream($callback, 200, $headers);
            }

            return view('sales.monthly', ['sale' => $current_month, 'sum' => $sum, 'first' => $first, 'latest' => $latest, 'count' => $count, 'getdate' => $getdate]);
        }
    
        public function compare(Request $request)
        {
            $sum = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $request['to_date']])
            ->sum('sales_amount');
            $secondsum = DB::table('sales')
            ->whereBetween('sold_date', [$request['compare_from_date'], $request['compare_to_date']])
            ->sum('sales_amount');
            $comparesum = $sum - $secondsum;
            if($sum != 0){
                $percentage = (($sum - $secondsum) / ($sum + $secondsum)/2) * 100;
            }else{
                $percentage = 0;
            }
            $getfromdate = $request['from_date'];
            $gettodate = $request['to_date'];
            $getsecondfromdate = $request['compare_from_date'];
            $getsecondtodate = $request['compare_to_date'];

            $first = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $request['to_date']])->first();
            $latest = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $request['to_date']])->orderBy('sold_date', 'desc')->first();
            $count = DB::table('sales')
            ->whereBetween('sold_date', [$request['from_date'], $request['to_date']])->orderBy('sold_date', 'desc')->Count();

            $secondfirst = DB::table('sales')
            ->whereBetween('sold_date', [$request['compare_from_date'], $request['compare_to_date']])->first();
            $secondlatest = DB::table('sales')
            ->whereBetween('sold_date', [$request['compare_from_date'], $request['compare_to_date']])->orderBy('sold_date', 'desc')->first();
            $secondcount = DB::table('sales')
            ->whereBetween('sold_date', [$request['compare_from_date'], $request['compare_to_date']])->orderBy('sold_date', 'desc')->Count();

            $firstcompare = Sales::whereBetween('sold_date', [$request['from_date'], $request['to_date']])->OrderBy('sold_date')->get();
            $secondcompare = Sales::whereBetween('sold_date', [$request['compare_from_date'], $request['compare_to_date']])->OrderBy('sold_date')->get();
            
            if($request->key == "comparekey"){
                $fileName = "Compare_First_$first->sold_date/_$latest->sold_date.csv";
             
                     $headers = array(
                         "Content-type"        => "text/csv",
                         "Content-Disposition" => "attachment; filename=$fileName",
                         "Pragma"              => "no-cache",
                         "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
                         "Expires"             => "0"
                     );
             
                     $columns = array('sold_id', 'sold_name', 'sold_date', 'sales_amount', 'sold_quantity');

                     $callback = function() use($firstcompare, $columns) {
                         $file = fopen('php://output', 'w');
                         fputcsv($file, $columns);
             
                         foreach ($firstcompare as $csv) {
                             $row['sold_id']  = $csv->sold_id;
                             $row['sold_name']    = $csv->sold_name;
                             $row['sold_date']    = $csv->sold_date;
                             $row['sales_amount']  = $csv->sales_amount;
                             $row['sold_quantity']  = $csv->sold_quantity;
                             fputcsv($file, array($row['sold_id'], $row['sold_name'], $row['sold_date'], $row['sales_amount'], $row['sold_quantity']));
                         }

resources/views/sales/compare.blade.php
@extends('layouts.special')

@section('content')

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<div class="col-md-10">
<h4 style="margin-top:25px;text-align:left !important;padding-left: 10%;">
   <u>Compare Sales Report</u>   
</h4>
</div>

<div class="col-md-5" style="display:inline-block;text-align:left !important;">
<h5 style="margin-top:25px;text-align:left !important;">
   First 
</h5>
    <table class="table">
        <thead>
            <tr class="table-warning">
            <td>ID</td>
            <td>Sales ID</td>
            <td>Sales Date</td>
            <td>Sales Amount</td>
            </tr>
        </thead>

        <tbody>
            @foreach($sale as $sales)
            <tr>
                <td>{{$sales->id}}</td>
                <td>{{$sales->sold_id}}</td>
                <td>{{$sales->sold_date}}</td>
                <td>{{$sales->sales_amount}}</td>
                <td class="text-center">
            </tr>
            @endforeach
        </tbody>
    </table>
</div>

<div class="col-md-5" style="display:inline-block;text-align:left !important;">
<h5 style="margin-top:25px;text-align:left !important;">
   Second  
</h5>
    <table class="table">
        <thead>
            <tr class="table-warning">
            <td>ID</td>
            <td>Sales ID</td>
            <td>Sales Date</td>
            <td>Sales Amount</td>
            </tr>
        </thead>
        <tbody>

        @foreach($secondsale as $secondsales)
        <tr>
            <td>{{$secondsales->id}}</td>
            <td>{{$secondsales->sold_id}}</td>
            <td>{{$secondsales->sold_date}}</td>
            <td>{{$secondsales->sales_amount}}</td>
            <td class="text-center">
 
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>
</div>

<div class="col-md-5" style="display:inline-block;text-align:left !important;">
Summarized Report
    <table class="table">
        <thead>
            <tr class="table-warning">
                <td>Total Sales Report</td>
                <td>Sales Date</td>
                <td>Sales Amount</td>
            </tr>
        </thead>

        <tr>
            <td>{{$count ?? ''}}</td>
            <td>{{$first->sold_date ?? ''}} - {{$latest->sold_date ?? ''}}</td>
            <td>{{$sum ?? ''}}</td>
        </tr>
    </table>
</div>

<div class="col-md-5" style="display:inline-block;text-align:left !important;">
    Summarized Report
        <table class="table">
            <thead>
                <tr class="table-warning">
                    <td>Total Sales Report</td>
                    <td>Sales Date</td>
                    <td>Sales Amount</td>
                </tr>
            </thead>

            <tr>
                <td>{{$secondcount ?? ''}}</td>
                <td>{{$secondfirst->sold_date ?? ''}} - {{$secondlatest->sold_date ?? ''}}</td>
                <td>{{$secondsum ?? ''}}</td>
            </tr>
        </tbody>
    </table>
    </div>

<form method="post" action="{{ route('comparedate') }}">
    <div class="col-md-5" style="display:inline-block;text-align:left !important;">
           <div class="form-group">
                @csrf
              <label for="sales_date">From Date</label>
              <input type="date" class="form-control" name="from_date" value="{{$getfromdate ?? ''}}"/>
          </div>

          <div class="form-group">
              <label for="sales_date">To Date</label>
              <input type="date" class="form-control" name="to_date" value="{{$gettodate ?? ''}}"/>
          </div>
    </div>
    <div class="col-md-5" style="display:inline-block;text-align:left !important;">
          <div class="form-group">
              <label for="sales_date">From Date</label>
              <input type="date" class="form-control" name="compare_from_date" value="{{$getsecondfromdate ?? ''}}"/>
          </div>

          <div class="form-group">
              <label for="sales_date">To Date</label>
              <input type="date" class="form-control" name="compare_to_date" value="{{$getsecondtodate ?? ''}}"/>
          </div>
    </div>
    <div class="col-md-10" style="display:inline-block;margin-top:25px">
          <button type="submit" class="btn btn-block btn-danger">Search</button>
    <div>
</form>

@if($count != 0)
<form method="post" action="{{ route('comparedate') }}">
    @csrf
    <input type="date" class="form-control" name="from_date" value="{{$getfromdate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="to_date" value="{{$gettodate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="compare_from_date" value="{{$getsecondfromdate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="compare_to_date" value="{{$getsecondtodate ?? ''}}" hidden/>
    <input type="text" class="form-control" name="key" value="comparekey" hidden/>
    <div style="display:inline-block;margin-top:25px;width:100%">
        <button type="submit" class="btn btn-block btn-danger">Generate First Data CSV Report</button>
    <div>
</form>
@endif

@if($secondcount != 0)
<form method="post" action="{{ route('comparedate') }}">
    @csrf
    <input type="date" class="form-control" name="from_date" value="{{$getfromdate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="to_date" value="{{$gettodate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="compare_from_date" value="{{$getsecondfromdate ?? ''}}" hidden/>
    <input type="date" class="form-control" name="compare_to_date" value="{{$getsecondtodate ?? ''}}" hidden/>
    <input type="text" class="form-control" name="secondkey" value="comparesecondkey" hidden/>
    <div style="display:inline-block;margin-top:25px;width:100%">
        <button type="submit" class="btn btn-block btn-danger">Generate Second Data CSV Report</button>
    <div>
</form>
@endif

<h6 style="margin-top:75px;color:#DC143C;text-align:left !important">
    <b>Compare Report Results based on date selected</b>  
</h6>
    <table class="table" style="margin-top:25px">
        <thead>
            <tr class="table-warning">
                <td>Total Sales Report</td>
                <td>First Sales Date || Second Sales Data</td>
                <td>Sales Amount</td>
                <td>Profit Percentage</td>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td>{{$count ?? ''}} || {{$secondcount ?? ''}}</td>
                <td>{{$first->sold_date ?? ''}} - {{$latest->sold_date ?? ''}} || {{$secondfirst->sold_date ?? ''}} - {{$secondlatest->sold_date ?? ''}}</td>
                <td>{{$comparesum ?? ''}}</td>
                <td>{!! number_format((float)($percentage),2) ?? ''!!}%</td>
            </tr>
        </tbody>
  </table>
@endsection

resources/views/sales/create.blade.php
@extends('layouts.app')

@section('content')




<div class="push-top">
  @if(session()->get('alert'))
    <div class="alert alert-danger">
      {{ session()->get('alert') }}  
    </div>
  @endif
</div>
<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="push-top">
  @if(session()->get('stock'))
    <div class="alert alert-warning">
      {{ session()->get('stock') }}  
    </div>
  @endif
</div>

<div class="card push-top">
  <div class="card-header">
    <h5>
      Add Item Sold
    </h5> 
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('sales.store') }}">
                @csrf
          <div class="form-group">
              <label for="duplicate">Item Name</label>
              <select class="js-example-basic-single form-control" style="width:100%" name="duplicate" id='singleSelectValueDDjQuery'>
                  <option value="" disabled selected>--Select--</option>
                @foreach($items as $item)
                  <option value="{{$item->sold_name}}" data-othervalue="{{$item->quantity}}" data-othervalue-2="{{$item->price}}" data-othervalue-3="{{$item->category}}">{{$item->item_name}}</option>
                @endforeach
              </select>
          </div>

          <input type="text" class="form-control" name="sold_name" id="hidden_sold_name" hidden/>

          <div class="form-group">
              <label for="sold_date">Sold Date</label>
              <input type="date" class="form-control" name="sold_date"/>
          </div>
              <input type="text" class="form-control" name="category" id="itemcategory" hidden/>
          <div class="form-group">
              <label for="sold_quantity">Sold Quantity</label>
              <input type="text" class="form-control" name="sold_quantity" id="totalquantity"/>
          </div>
          <div class="form-group">
              <label for="sales_amount">Quantity Left: <a href="http://127.0.0.1:8000/items" id="list_quantity"></a><a id="second_list_quantity"></a></label><br>
              <label for="sales_amount">Each Item Amount</label>
              <input readonly type="text" class="form-control" name="sales_amount" id='each'/>
          </div>
          <div class="form-group">
              <label for="sales_amount">Total Sales Amount</label>
              <input readonly type="text" class="form-control" name="sales_amount" id='textFieldValueJQ'/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Create Sales Record</button>
      </form>

      <a href="{{url('sales')}}" class="btn btn-block btn-info" style="margin-top:25px">Show Sales Record List</a>
  </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>

<script>
$("#singleSelectValueDDjQuery").on("change",function(){
        //Getting Value
        var otherValue=$(this).find('option:selected').attr('data-othervalue');
        var otherValue2=$(this).find('option:selected').attr('data-othervalue-2');
        var otherValue3=$(this).find('option:selected').attr('data-othervalue-3');
        var selValue = $("#singleSelectValueDDjQuery option:selected").text();
        var settotalValue = otherValue2 * $('#totalquantity').val()
        //Setting Value
        $("#textFieldValueJQ").val(settotalValue);
        $("#each").val(otherValue2);
        $("#second").val(otherValue2);
        $("#hidden_sold_name").val(selValue);
        $("#itemcategory").val(otherValue3);
        if(otherValue == 0){
          document.getElementById("list_quantity").innerHTML = otherValue + " (Please Restock)"; 
        }
        else if(otherValue > 0 && otherValue <= 10){
          document.getElementById("list_quantity").innerHTML = otherValue + " (Nearly Out of Stock)"; 
        }
        else{
          document.getElementById("list_quantity").innerHTML = otherValue; 
        }
    });
    </script>

<script>
$("#totalquantity").on("change",function(){
        //Getting Value
        var otherValue3=$("#singleSelectValueDDjQuery").find('option:selected').attr('data-othervalue-2');
        var settotalValue = otherValue3 * $('#totalquantity').val()
        //Setting Value
        $("#textFieldValueJQ").val(settotalValue);
    });
</script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
@endsection

resources/views/sales/edit.blade.php
@extends('layouts.app')

@section('content')

<style>
    .container {
      max-width: 450px;
    }
    .push-top {
      margin-top: 50px;
    }
</style>

<div class="push-top">
  @if(session()->get('alert'))
    <div class="alert alert-danger">
      {{ session()->get('alert') }}  
    </div>
  @endif
</div>
<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="push-top">
  @if(session()->get('stock'))
    <div class="alert alert-warning">
      {{ session()->get('stock') }}  
    </div>
  @endif
</div>

<div class="card push-top">
  <div class="card-header">
    Edit & Update
  </div>

  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('sales.update', $sale->id) }}">
          <div class="form-group">
              @csrf
              @method('PATCH')
              <label for="sales_id">Item Name</label>
              <input type="text" class="form-control" name="sold_name" value="{{$sale->sold_name}}" disabled/>
              <input type="text" class="form-control" name="sold_name" value="{{$sale->sold_name}}" hidden/>
          </div>
          <div class="form-group">
              <label for="sales_date">Sales Date</label>
              <input type="date" class="form-control" name="sold_date" value="{{$sale->sold_date}}"/>
          </div>
          <input type="text" class="form-control" name="category" value="{{$sale->category}}" hidden/>
          <input type="text" class="form-control" name="created_at" value="{{$sale->created_at}}" hidden/>
          <div class="form-group">
              <label for="sales_amount">Sold Quantity</label>
              <input type="text" class="form-control" name="sold_quantity" value="{{$sale->sold_quantity}}" id="totalquantity"/>
          </div>
          <div class="form-group">
              <label for="sales_amount">Quantity Left: <a href="http://127.0.0.1:8000/items" id="list_quantity">{{$each_amount->quantity}}</a></label><br>
              <label for="sales_amount">Each Item Amount</label>
              <input readonly type="text" class="form-control" name="each_sales_amount" id='each' value="{{$each_amount->price}}"/>
          </div>
          <div class="form-group">
              <label for="sales_amount">Total Sales Amount</label>
              <input type="text" class="form-control" name="sales_amount" value="{{$sale->sales_amount}}" id="textFieldValueJQ" disabled/>
              <input type="text" class="form-control" name="sales_amount" value="{{$sale->sales_amount}}" id="textFieldValueJQQ" hidden/>
          </div>
          <button type="submit" class="btn btn-block btn-danger">Update Sales</button>
      </form>
  </div>
</div>

<script>
$("#totalquantity").on("change",function(){
        //Getting Value
        var settotalValue = $('#totalquantity').val() * $("#each").val()
        //Setting Value
        $("#textFieldValueJQ").val(settotalValue);
        $("#textFieldValueJQQ").val(settotalValue);
    });
    </script>
@endsection

resources/views/sales/index.blade.php
@extends('layouts.app')

@section('content')

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>  

<div class="push-top">
  @if(session()->get('delete'))
    <div class="alert alert-danger">
      {{ session()->get('delete') }}  
    </div>
  @endif
</div>
  
<div class="push-top">
  @foreach($restock_item as $item)
      @if($item->quantity == 0)
        <div class="alert alert-info">
          Please Restock {{$item->item_name}} !
        </div>
      @endif
    @endforeach
</div>


  <table class="table" style="width:800px;">
    <thead>
        <tr class="table-warning">
          <td>ID</td>
          <td>Sales ID</td>
          <td>Sales Name</td>
          <td>Sales Date</td>
          <td>Sold Quantity</td>
          <td>Sales Amount</td>
          <td class="text-center">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($sale as $sales)
        <tr>
            <td>{{$sales->id}}</td>
            <td>{{$sales->sold_id}}</td>
            <td>{{$sales->sold_name}}</td>
            <td>{{$sales->sold_date}}</td>
            <td>{{$sales->sold_quantity}} pcs</td>
            <td>RM {{$sales->sales_amount}}</td>
            <td class="text-center">
                <a href="{{ route('sales.edit', $sales->id)}}" class="btn btn-primary btn-sm">Edit</a>
                <form action="{{ route('sales.destroy', $sales->id)}}" method="post" style="display: inline-block">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/sales/monthly.blade.php
@extends('layouts.app')

@section('content')

<style>
  .push-top {
    margin-top: 50px;
  }
</style>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>

<h4 style="margin-top:25px">
   <u>Monthly Sales Report</u>   
</h4>

<div class="push-top">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif

  <form method="post" action="{{ route('monthdate') }}">
    <div class="form-group">
        @csrf
        <label for="sales_date">Sales Date</label>
        <input type="date" class="form-control" name="from_date" value="{{$getdate ?? ''}}"/>
    </div>

    <button type="submit" class="btn btn-block btn-danger">Create Monthly Report</button>
  </form>

  @if($count != 0)
  <form method="post" action="{{ route('monthdate') }}">
    <div class="form-group">
        @csrf
        <input type="date" class="form-control" name="from_date" value="{{$getdate ?? ''}}" hidden/>
    </div>
    <input type="text" class="form-control" name="key" value="monthkey" hidden/>
    <button type="submit" class="btn btn-block btn-danger">Generate CSV File</button>
  </form>
  @endif

  <!-- Search Results -->
  <h6 style="margin-top:50px">
    Sales Record List based on date selected (Monthly-based)  
  </h6>
  <table class="table">
      <thead>
          <tr class="table-warning">
            <td>ID</td>
            <td>Sales ID</td>
            <td>Sales Date</td>
            <td>Sales Amount</td>
          </tr>
      </thead>

      @foreach($sale as $sales)
      <tr>
          <td>{{$sales->id}}</td>
          <td>{{$sales->sold_id}}</td>
          <td>{{$sales->sold_date}}</td>
          <td>{{$sales->sales_amount}}</td>
          <td class="text-center">
      </tr>
      @endforeach

  </table>  

  <hr class ="hr-sales">

  <!-- Report Results -->
  <h6 style="margin-top:75px;color:#DC143C">
    <b>Report Results based on date selected (Monthly-based)</b>  
  </h6>
  <table class="table" style="margin-top:25px">
      <thead>
          <tr class="table-warning">
          <td>Total ID(s)</td>
          <td>Sales Date</td>
          <td>Total Sales Amount</td>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{$count ?? ''}}</td>
              <td>{{$first->sold_date ?? ''}} - {{$latest->sold_date ?? ''}}</td>
              <td>{{$sum ?? ''}}</td>
                  </form>
              </td>
          </tr>
      </tbody>
  </table>
<div>
    
@endsection